import { Router } from "express";
import { CartController } from './../controllers/cart';
const cartRouter = Router();
cartRouter.get("/:userId",CartController.getCartByUserId);
cartRouter.post("/",CartController.addItemToCart);
cartRouter.put("/",CartController.updateProductQuantity);
cartRouter.delete("/remove/:userId/:productId",CartController.removeFromCart);
cartRouter.post("/increase",CartController.increaseProductQuantity);
cartRouter.post("/decrease",CartController.decreaseProductQuantity);
export default cartRouter;
